version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotify-clone
    restart: unless-stopped
volumes:
  db_data:
